version: '3.4'

services:
  radancybanking:
    image: ${DOCKER_REGISTRY-}radancybanking
    build:
      context: .
      dockerfile: RadancyBanking/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"